name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_KEY: ${{ secrets.KEY }}
          file_name: .env
          fail_on_empty: true

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.75.0
      
      - name: Build
        run: cargo build --verbose --release
      
      - name: Test
        run: cargo test --verbose --release --features async
